name: Convert then Deploy

env:
  APP_NAME: addr-jp-api

on:
  push:
    branches:
      - "**"
  release:
    types: [published]

jobs:
  convert-then-deploy:
    runs-on: ubuntu-latest
    name: Convert CSV to DB then Deploy to Heroku
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.5"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "::add-path::$HOME/.poetry/bin"
      - name: Install dependencies
        run: |
          poetry install
      - name: Convert CSV to DB
        run: |
          make convert
      - name: Deploy to Heroku
        if: startsWith(github.ref, 'refs/tags/v') && github.event_name != 'pull_request'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku plugins:install heroku-builds
          make deploy
